# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphs.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 890)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setStyleSheet("background-color: #060606;")
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setStyleSheet("background-color: #060606;")
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_grid = QtWidgets.QGridLayout()
        self.main_grid.setContentsMargins(10, 10, 10, 10)
        self.main_grid.setSpacing(0)
        self.main_grid.setObjectName("main_grid")
        self.tabWidget = QtWidgets.QTabWidget(self.central_widget)
        self.tabWidget.setStyleSheet("font: 25 16pt \"Bahnschrift Light Condensed\";\n"
                                     "background-color: #ffffff;")
        self.tabWidget.setObjectName("tabWidget")
        self.alt_tab = QtWidgets.QWidget()
        self.alt_tab.setObjectName("alt_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.alt_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.alt_tab)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 25 16pt \"Bahnschrift Light\";\n"
                                 "padding-top: 1.25em;")
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.max_alt_label = QtWidgets.QLabel(self.alt_tab)
        self.max_alt_label.setStyleSheet("font: 36pt \"Impact\";\n"
                                         "padding-left: .1em;")
        self.max_alt_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.max_alt_label.setObjectName("max_alt_label")
        self.gridLayout.addWidget(self.max_alt_label, 0, 1, 1, 4)
        self.tabWidget.addTab(self.alt_tab, "")
        self.speed_tab = QtWidgets.QWidget()
        self.speed_tab.setObjectName("speed_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.speed_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.speed_tab)
        self.label_7.setStyleSheet("font: 25 16pt \"Bahnschrift Light\";\n"
                                   "padding-top: 1.25em;")
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.max_speed_label = QtWidgets.QLabel(self.speed_tab)
        self.max_speed_label.setStyleSheet("font: 36pt \"Impact\";\n"
                                           "padding-left: .1em;")
        self.max_speed_label.setObjectName("max_speed_label")
        self.gridLayout_2.addWidget(self.max_speed_label, 0, 1, 1, 4)
        self.tabWidget.addTab(self.speed_tab, "")
        self.gforce_tab = QtWidgets.QWidget()
        self.gforce_tab.setObjectName("gforce_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gforce_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gforce_tab)
        self.label_2.setStyleSheet("font: 25 16pt \"Bahnschrift Light\";\n"
                                   "padding-top: 1.25em;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.max_gforce_label = QtWidgets.QLabel(self.gforce_tab)
        self.max_gforce_label.setStyleSheet("font: 36pt \"Impact\";\n"
                                            "padding-left: .1em;")
        self.max_gforce_label.setObjectName("max_gforce_label")
        self.gridLayout_3.addWidget(self.max_gforce_label, 0, 1, 1, 4)
        self.tabWidget.addTab(self.gforce_tab, "")
        self.pressure_tab = QtWidgets.QWidget()
        self.pressure_tab.setObjectName("pressure_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pressure_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.pressure_tab)
        self.label_4.setStyleSheet("font: 25 16pt \"Bahnschrift Light\";\n"
                                   "padding-top: 1.25em;")
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.max_pressure_label = QtWidgets.QLabel(self.pressure_tab)
        self.max_pressure_label.setStyleSheet("font: 36pt \"Impact\";\n"
                                              "padding-left: .1em;")
        self.max_pressure_label.setObjectName("max_pressure_label")
        self.gridLayout_4.addWidget(self.max_pressure_label, 0, 1, 1, 4)
        self.tabWidget.addTab(self.pressure_tab, "")
        self.temp_tab = QtWidgets.QWidget()
        self.temp_tab.setObjectName("temp_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.temp_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.max_cube_temp_label = QtWidgets.QLabel(self.temp_tab)
        self.max_cube_temp_label.setStyleSheet("font: 36pt \"Impact\";\n"
                                               "padding-left: .1em;")
        self.max_cube_temp_label.setObjectName("max_cube_temp_label")
        self.gridLayout_5.addWidget(self.max_cube_temp_label, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.temp_tab)
        self.label_13.setStyleSheet("font: 25 16pt \"Bahnschrift Light\";\n"
                                    "padding-top: 1.25em;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.temp_tab)
        self.label_6.setStyleSheet("font: 25 16pt \"Bahnschrift Light\";\n"
                                   "padding-top: 1.25em;")
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.max_bat_temp_label = QtWidgets.QLabel(self.temp_tab)
        self.max_bat_temp_label.setStyleSheet("font: 36pt \"Impact\";\n"
                                              "padding-left: .1em;")
        self.max_bat_temp_label.setObjectName("max_bat_temp_label")
        self.gridLayout_5.addWidget(self.max_bat_temp_label, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.temp_tab)
        self.label_8.setStyleSheet("font: 25 16pt \"Bahnschrift Light\";\n"
                                   "padding-top: 1.25em;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 2, 1, 1)
        self.max_motor_temp_label = QtWidgets.QLabel(self.temp_tab)
        self.max_motor_temp_label.setStyleSheet("font: 36pt \"Impact\";\n"
                                                "padding-left: .1em;")
        self.max_motor_temp_label.setObjectName("max_motor_temp_label")
        self.gridLayout_5.addWidget(self.max_motor_temp_label, 0, 5, 1, 1)
        self.tabWidget.addTab(self.temp_tab, "")
        self.main_grid.addWidget(self.tabWidget, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.main_grid)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p>Max Altitude: </p><p><span style=\" text-decoration: underline; color:#ffcd00;\">______________</span></p></body></html>"))
        self.max_alt_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alt_tab), _translate("MainWindow", "Altitude"))
        self.label_7.setText(_translate("MainWindow",
                                        "<html><head/><body><p>Max Speed: </p><p><span style=\" text-decoration: underline; color:#ffcd00;\">____________</span></p></body></html>"))
        self.max_speed_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.speed_tab), _translate("MainWindow", "Speed"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p>Max G-Force: </p><p><span style=\" text-decoration: underline; color:#ffcd00;\">_______________</span></p></body></html>"))
        self.max_gforce_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gforce_tab), _translate("MainWindow", "G-Force"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p>Max Pressure: </p><p><span style=\" text-decoration: underline; color:#ffcd00;\">________________</span></p></body></html>"))
        self.max_pressure_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pressure_tab), _translate("MainWindow", "Pressure"))
        self.max_cube_temp_label.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow",
                                         "<html><head/><body><p>Max Motor Temp: </p><p><span style=\" text-decoration: underline; color:#0055ff;\">_____________________</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p>Max Battery Temp: </p><p><span style=\" text-decoration: underline; color:#ffcd00;\">____________________</span></p></body></html>"))
        self.max_bat_temp_label.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow",
                                        "<html><head/><body><p>Max Cubesat Temp: </p><p><span style=\" text-decoration: underline; color:#ff0000;\">_____________________</span></p></body></html>"))
        self.max_motor_temp_label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.temp_tab), _translate("MainWindow", "Temperatures"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
